name: Build Desktop Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      # Compile first to capture Kotlin errors with plain logs
      - name: Compile Kotlin (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          set -o pipefail
          ./gradlew :composeApp:compileKotlinDesktop --warning-mode all --stacktrace --console=plain --no-daemon 2>&1 | tee compile-macos.log

      - name: Compile Kotlin (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          .\gradlew.bat :composeApp:compileKotlinDesktop --warning-mode all --stacktrace --console=plain --no-daemon *>&1 | Tee-Object -FilePath compile-windows.log

      # If compilation failed, show last lines and upload logs
      - name: Show Kotlin error tail (macOS)
        if: failure() && runner.os == 'macOS'
        shell: bash
        run: |
          echo "==== Last 200 lines of Kotlin compile log ===="
          tail -n 200 compile-macos.log || true

      - name: Show Kotlin error tail (Windows)
        if: failure() && runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "==== Last 200 lines of Kotlin compile log ===="
          Get-Content compile-windows.log -Tail 200 -ErrorAction SilentlyContinue

      - name: Upload compile logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compile-logs-${{ matrix.os }}
          path: |
            compile-*.log
            **/kotlin-daemon.*.log
          if-no-files-found: ignore

      - name: Build macOS DMG
        if: runner.os == 'macOS'
        run: ./gradlew packageDmg --stacktrace --info --no-daemon

      - name: Build Windows MSI
        if: runner.os == 'Windows'
        run: ./gradlew packageMsi --stacktrace --info --no-daemon

      - name: Upload macOS Artifact
        if: runner.os == 'macOS' && success()
        uses: actions/upload-artifact@v4
        with:
          name: ENDEcode-macos
          path: composeApp/build/compose/binaries/main/dmg/*.dmg
          if-no-files-found: error
          compression-level: 0

      - name: Upload Windows Artifact
        if: runner.os == 'Windows' && success()
        uses: actions/upload-artifact@v4
        with:
          name: ENDEcode-windows
          path: composeApp/build/compose/binaries/main/msi/*.msi
          if-no-files-found: error
          compression-level: 0

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}
          path: |
            composeApp/build/reports/
            composeApp/build/logs/
            **/hs_err_pid*.log
          if-no-files-found: ignore
