name: Build Desktop Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build macOS DMG
        if: runner.os == 'macOS'
        run: ./gradlew packageDmg --stacktrace --info --no-daemon

      - name: Build Windows MSI
        if: runner.os == 'Windows'
        run: ./gradlew packageMsi --stacktrace --info --no-daemon

      - name: Upload macOS Artifact
        if: runner.os == 'macOS' && success()
        uses: actions/upload-artifact@v4
        with:
          name: ENDEcode-macos
          path: composeApp/build/compose/binaries/main/dmg/*.dmg
          if-no-files-found: error
          compression-level: 0

      - name: Upload Windows Artifact
        if: runner.os == 'Windows' && success()
        uses: actions/upload-artifact@v4
        with:
          name: ENDEcode-windows
          path: composeApp/build/compose/binaries/main/msi/*.msi
          if-no-files-found: error
          compression-level: 0

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}
          path: |
            composeApp/build/reports/
            composeApp/build/logs/
            **/hs_err_pid*.log
          if-no-files-found: ignore
