name: Build Multi-Platform Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: 'x64'

      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Install Rosetta
        if: runner.os == 'macOS'
        run: softwareupdate --install-rosetta --agree-to-license

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Build macOS DMG
        if: runner.os == 'macOS'
        run: ./gradlew packageDmg

      - name: Build Windows EXE
        if: runner.os == 'Windows'
        run: ./gradlew packageMsi

      - name: Build Linux DEB
        if: runner.os == 'Linux'
        run: ./gradlew packageDeb

      - name: Upload macOS Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: ENDEcode-macos
          path: composeApp/build/compose/binaries/main/dmg/ENDEcode-*.dmg

      - name: Upload Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: ENDEcode-windows
          path: composeApp/build/compose/binaries/main/msi/ENDEcode-*.msi

      - name: Upload Linux Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: ENDEcode-linux
          path: composeApp/build/compose/binaries/main/deb/endecode_*.deb